version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "9433:1433"
    networks:
      - kfc-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'P@ssw0rd' -Q 'SELECT 1' -C -N"]
      interval: 10s
      timeout: 5s
      retries: 5
    kfc-app:
     depends_on:
      kfc-project_mssql_1:
        condition: service_healthy

  kfc-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;database=chufa;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd
    depends_on:
      mssql:
        condition: service_healthy
    networks:
      - kfc-network

networks:
  kfc-network:
