#資料庫連線設定
spring:  
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.50.90:1433;database=chufa;trustServerCertificate=true
    username: sa
    password: P@ssw0rd
  mvc:
    converters:
      preferred-json-mapper: jackson
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  web:
    resources:
      static-locations=classpath: /static/

  #Hibernate/JPA的相關設定
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#thymeleaf
  thymeleaf:
    enabled: true
    encoding: UTF-8
    mode: HTML
    cache: false
    prefix: classpath:/templates
    suffix: .html

#i18n
  messages:
    basename: messages
    encoding: UTF-8

jwt:
  token:
    expire: 10
    
server:
  address: 0.0.0.0
  port: 8080